export function buildFallbackExtraction() {
  return {
    header: {
      supplierName: "",
      tin: "",
      vrn: "",
      serialNumber: "",
      receiptNumber: "",
      verificationCode: "",
      receiptDate: new Date().toISOString().slice(0, 10),
      receiptTime: "",
      traReceiptNumber: "",
      invoiceReference: "",
      paymentMethod: "",
      taxOffice: "",
      currency: "USD",
      itemCount: 0,
      subtotal: 0,
      tax: 0,
      total: 0
    },
    fieldConfidence: {
      supplierName: "UNREADABLE",
      tin: "UNREADABLE",
      vrn: "UNREADABLE",
      serialNumber: "UNREADABLE",
      receiptNumber: "UNREADABLE",
      verificationCode: "UNREADABLE",
      receiptDate: "LOW",
      receiptTime: "UNREADABLE",
      traReceiptNumber: "UNREADABLE",
      invoiceReference: "UNREADABLE",
      paymentMethod: "UNREADABLE",
      taxOffice: "UNREADABLE",
      subtotal: "UNREADABLE",
      tax: "UNREADABLE",
      total: "UNREADABLE",
      itemCount: "UNREADABLE"
    },
    fieldSource: {
      supplierName: "NONE",
      tin: "NONE",
      vrn: "NONE",
      serialNumber: "NONE",
      receiptNumber: "NONE",
      verificationCode: "NONE",
      receiptDate: "DERIVED",
      receiptTime: "NONE",
      traReceiptNumber: "NONE",
      invoiceReference: "NONE",
      paymentMethod: "NONE",
      taxOffice: "NONE",
      subtotal: "NONE",
      tax: "NONE",
      total: "NONE",
      itemCount: "NONE"
    },
    lines: [],
    warnings: ["Unable to extract receipt data automatically. You can continue with manual entry."],
    rawTextPreview: "",
    extractionMethod: "NONE",
    scanStatus: "UNREADABLE",
    receiptType: "UNCLEAR",
    preprocessingApplied: [],
    qr: {
      detected: false,
      rawValue: "",
      normalizedRawValue: "",
      contentType: "NONE",
      isTraVerification: false,
      isQrOnlyImage: false,
      decodeStatus: "NOT_DETECTED",
      decodePass: "",
      parseStatus: "UNPARSED",
      failureReason: "No QR detected",
      verificationUrl: "",
      parsedFields: {},
      confidence: "UNREADABLE",
      warnings: [],
      stages: {
        decode: {
          success: false,
          status: "NOT_DETECTED",
          pass: "",
          reason: "No QR detected"
        },
        classification: {
          success: false,
          type: "NONE",
          isTraUrl: false
        },
        verificationLookup: {
          attempted: false,
          success: false,
          status: "NOT_ATTEMPTED",
          reason: "",
          httpStatus: null,
          parsed: false
        }
      }
    },
    scanDiagnostics: {
      qrDetected: false,
      qrDecodeStatus: "NOT_DETECTED",
      qrDecodePass: "",
      qrParseStatus: "UNPARSED",
      qrFailureReason: "No QR detected",
      qrContentType: "NONE",
      qrRawValue: "",
      qrNormalizedRawValue: "",
      qrRawLength: 0,
      qrRawPreview: "",
      qrRawPayloadFormat: "EMPTY",
      qrVerificationUrl: "",
      qrIsTraVerification: false,
      qrParsedFieldCount: 0,
      qrParsedLineItemsCount: 0,
      qrLookupStatus: "NOT_ATTEMPTED",
      qrLookupReason: "",
      qrLookupHttpStatus: null,
      qrLookupParsed: false,
      ocrAttempted: false,
      ocrSucceeded: false,
      ocrError: "",
      scanStatus: "UNREADABLE",
      extractionMethod: "NONE",
      returnedFrom: "qr_tra",
      failureStage: "QR_NOT_DETECTED"
    }
  };
}
