// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/activity-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity-log">> = Specific
  const handler = {} as typeof import("../../src/app/activity-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alerts-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alerts-center">> = Specific
  const handler = {} as typeof import("../../src/app/alerts-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/breakdowns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/breakdowns">> = Specific
  const handler = {} as typeof import("../../src/app/breakdowns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/clients/[clientId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients/[clientId]">> = Specific
  const handler = {} as typeof import("../../src/app/clients/[clientId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients">> = Specific
  const handler = {} as typeof import("../../src/app/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/clients/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients/setup">> = Specific
  const handler = {} as typeof import("../../src/app/clients/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cost-tracking/budget-vs-actual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cost-tracking/budget-vs-actual">> = Specific
  const handler = {} as typeof import("../../src/app/cost-tracking/budget-vs-actual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cost-tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cost-tracking">> = Specific
  const handler = {} as typeof import("../../src/app/cost-tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data-quality/linkage-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-quality/linkage-center">> = Specific
  const handler = {} as typeof import("../../src/app/data-quality/linkage-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drilling-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drilling-reports">> = Specific
  const handler = {} as typeof import("../../src/app/drilling-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../src/app/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/setup">> = Specific
  const handler = {} as typeof import("../../src/app/employees/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/executive-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/executive-overview">> = Specific
  const handler = {} as typeof import("../../src/app/executive-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forecasting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forecasting">> = Specific
  const handler = {} as typeof import("../../src/app/forecasting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/issues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/issues">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/issues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/items">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/locations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/locations">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/locations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/receipt-intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/receipt-intake">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/receipt-intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/stock-movements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/stock-movements">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/stock-movements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/suppliers">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mechanics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mechanics">> = Specific
  const handler = {} as typeof import("../../src/app/mechanics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profit">> = Specific
  const handler = {} as typeof import("../../src/app/profit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/setup">> = Specific
  const handler = {} as typeof import("../../src/app/projects/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/purchasing/receipt-follow-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchasing/receipt-follow-up">> = Specific
  const handler = {} as typeof import("../../src/app/purchasing/receipt-follow-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/revenue">> = Specific
  const handler = {} as typeof import("../../src/app/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rigs/[rigId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rigs/[rigId]">> = Specific
  const handler = {} as typeof import("../../src/app/rigs/[rigId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rigs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rigs">> = Specific
  const handler = {} as typeof import("../../src/app/rigs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rigs/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rigs/setup">> = Specific
  const handler = {} as typeof import("../../src/app/rigs/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../src/app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/copilot/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/copilot/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/copilot/contextual-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/contextual-chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/copilot/contextual-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/copilot/executive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/executive">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/copilot/executive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/copilot/linkage-suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/linkage-suggestions">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/copilot/linkage-suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/copilot/threads/[threadId]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/threads/[threadId]/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/copilot/threads/[threadId]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/copilot/threads/[threadId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/threads/[threadId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/copilot/threads/[threadId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/copilot/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/threads">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/copilot/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alerts-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts-center">> = Specific
  const handler = {} as typeof import("../../src/app/api/alerts-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/approvals/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approvals/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/approvals/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/breakdowns/[breakdownId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/breakdowns/[breakdownId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/breakdowns/[breakdownId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/breakdowns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/breakdowns">> = Specific
  const handler = {} as typeof import("../../src/app/api/breakdowns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/budgets/plans/[planId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/budgets/plans/[planId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/budgets/plans/[planId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/budgets/plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/budgets/plans">> = Specific
  const handler = {} as typeof import("../../src/app/api/budgets/plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/budgets/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/budgets/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/budgets/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/[clientId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[clientId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/[clientId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cost-tracking/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cost-tracking/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/cost-tracking/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data-quality/linkage-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-quality/linkage-center">> = Specific
  const handler = {} as typeof import("../../src/app/api/data-quality/linkage-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drill-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drill-reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/drill-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drilling-reports/[reportId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drilling-reports/[reportId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/drilling-reports/[reportId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drilling-reports/[reportId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drilling-reports/[reportId]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/drilling-reports/[reportId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drilling-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drilling-reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/drilling-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[employeeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[employeeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[employeeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/[expenseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/[expenseId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/[expenseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/[expenseId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/[expenseId]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/[expenseId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/manual/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/manual">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/manual/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forecasting/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forecasting">> = Specific
  const handler = {} as typeof import("../../src/app/api/forecasting/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/intelligence/suggest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/intelligence/suggest">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/intelligence/suggest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/issues/auto-fix-naming/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/issues/auto-fix-naming">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/issues/auto-fix-naming/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/issues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/issues">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/issues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/items/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/items/[itemId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/items/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/items/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/items/merge">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/items/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/items">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/locations">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/movements/[movementId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/movements/[movementId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/movements/[movementId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/movements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/movements">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/movements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/receipt-intake/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/receipt-intake/commit">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/receipt-intake/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/receipt-intake/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/receipt-intake/extract">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/receipt-intake/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/receipt-intake/submissions/[submissionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/receipt-intake/submissions/[submissionId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/receipt-intake/submissions/[submissionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/receipt-intake/submissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/receipt-intake/submissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/receipt-intake/submissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/suppliers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/suppliers">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/suppliers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/usage-requests/[requestId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/usage-requests/[requestId]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/usage-requests/[requestId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/usage-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/usage-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/usage-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/maintenance-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/maintenance-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mechanics/directory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mechanics/directory">> = Specific
  const handler = {} as typeof import("../../src/app/api/mechanics/directory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profit/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profit/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/profit/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/requisitions/[requisitionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requisitions/[requisitionId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/requisitions/[requisitionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/requisitions/[requisitionId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requisitions/[requisitionId]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/requisitions/[requisitionId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/requisitions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requisitions">> = Specific
  const handler = {} as typeof import("../../src/app/api/requisitions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/requisitions/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requisitions/setup">> = Specific
  const handler = {} as typeof import("../../src/app/api/requisitions/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revenue/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revenue/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/revenue/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rigs/[rigId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rigs/[rigId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/rigs/[rigId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rigs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rigs">> = Specific
  const handler = {} as typeof import("../../src/app/api/rigs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/summary-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/summary-report">> = Specific
  const handler = {} as typeof import("../../src/app/api/summary-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
